/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2JAM7TnDt3c
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { useState } from "react";
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function Neons() {
  const [showEmailForm, setShowEmailForm] = useState(false);
  return (
    <div className="flex min-h-[100dvh] flex-col bg-black dark:bg-background">
      <header className="bg-primary text-primary-foreground py-2 px-4">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="text-lg font-bold" prefetch={false}>
            DW
          </Link>
          <nav className="flex items-center gap-4" />
        </div>
      </header>
      <section className="container mx-auto flex flex-col items-center justify-center gap-8 px-4 py-12 md:flex-row md:gap-16 md:py-24 lg:py-32">
        <div className="flex-1">
          <img
            src="/Neons Mockup 2.jpg"
            width={400}
            height={600}
            alt="Book Cover"
            className="mx-auto max-w-[300px] shadow-lg md:max-w-none"
            style={{ aspectRatio: "400/600", objectFit: "cover" }}
          />
        </div>
        <div className="flex-1 space-y-4 text-center text-white md:text-left">
          <h1 className="text-3xl font-bold tracking-tight text-white sm:text-4xl md:text-5xl">
            The Neons
          </h1>
          <p className="text-white dark:text-card-foreground">
            by Dylan Wiseman
          </p>
          <p className="text-white dark:text-card-foreground italic">
            Release Date: Sep 13, 2024
          </p>
          <div className="flex flex-col gap-2 sm:flex-row">
            <Link
              href="https://www.amazon.com/dp/B0DD1K4RCM"
              target="_blank noopener noreferrer"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-6 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              Pre-Order Kindle Version
            </Link>
            <button
              onClick={() => setShowEmailForm(true)}
              className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-neons-blue-light px-6 py-2 text-sm font-medium text-black shadow-sm transition-colors hover:bg-neons-blue-light/[.9] hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-white"
            >
              Waitlist for Paperback
            </button>
          </div>
          {showEmailForm && (
            <div className="mt-4 rounded-md bg-card p-4 shadow">
              <h3 className="text-lg font-medium">Join the Waitlist</h3>
              <p className="text-muted-foreground">
                Enter your email to be notified when the paperback is available.
              </p>
              <form className="mt-4 space-y-2">
                <Input type="email" placeholder="Enter your email" />
                <Button type="submit">Submit</Button>
              </form>
            </div>
          )}
        </div>
      </section>
      <section
        className="container mx-0 px-4 py-12 bg-black"
        style={{ maxWidth: "100%" }}
      >
        <div className="max-w-6xl space-y-4 mx-auto">
          <h4 className="text-xl font-bold tracking-tight text-white italic">
            The Story
          </h4>
          <p className="text-white dark:text-card-foreground">
            <span className="font-bold">
              A girl has gone missing—nothing unusual for the corrupt,
              crime-filled megacity of Xi, where biotechnical mods make everyone
              as unique and dangerous as their imaginations allow. Soon enough,
              no one will remember that the girl ever existed.
            </span>
            <br />
            <br />
            At least, that’s what Chance believes, until a duo of ambitious
            bounty hunters snatch him from his mundane day-to-day in the slums
            and introduce him to the shiny, secretive world of Xi’s rich and
            powerful. <br />
            <br />
            Meanwhile, in the city’s sparkling high-rises, a pair of siblings
            witness a murder and are forced into the violent bowels of the city,
            hunting for answers as they are hunted by a killer. <br />
            <br />A hard-punching, fast-paced cyberpunk fantasy,{" "}
            <span className="italic">The Neons</span> follows an ensemble cast
            of unlikely heroes as they untangle the wires of a twisted mystery
            and uncover a reality inhabited by cybernetic deities, android
            angels, and the resurrected demons of their own past lives.
          </p>
        </div>
      </section>
      <section
        className="container mx-0 px-4 py-12 bg-black"
        style={{ maxWidth: "100%" }}
      >
        <div className="max-w-6xl space-y-4 mx-auto">
          <h4 className="text-xl font-bold tracking-tight text-white italic">
            The Author
          </h4>
          <p className="text-white dark:text-card-foreground">
            This is my first book and I&apos;m figuring it all out as I go, so
            cut me some slack. <span className="italic">The Neons</span> started
            as a vague idea maybe 10 or 11 years ago and has morphed and
            materialized into what it is now as I synthesized and frankensteined
            together concepts, scenes, themes, styles, characters, and locations
            from different books, shows, and my real-life experiences.
            <br />
            <br />I have a penchant for immersive worldbuilding—the setting is a
            character itself—and nothing would make me happier than to one day
            see other authors write their own stories into the worlds I create.
            <br />
            <br />
            If you like my work, please leave me a review and let me know what
            (and who) you like best! If you don&apos;t like it, take a long
            walk, watch the sunset, maybe treat yourself to something sweet, and
            move on with your life as if you never read my books at all.
          </p>
        </div>
      </section>
    </div>
  );
}
